name = "mat"
version = "1.0.0"

description = "A simple and ergonomic string formatter for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "loipesmas", repo = "mat" }
links = [{ title = "Home", href = "https://github.com/loipesmas/mat" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
